### ISSUE TITLE
Sharing Data folder

### ISSUE THREAD

**Issue by MrUtOpiK** [senolem/dofuspetsbot#1]
Hi, 

Thanks for your script.
Could you share with use an example of your data folder ? When I try to take screenshot 5x5 in the lowest quality it does'nt works from my side.

Thanks for your help !

**Comment by loonsies** [comment]
Oh wow I'm sorry I never got any notification about your issue.
This is a Chacha. 
![image](https://user-images.githubusercontent.com/37041587/116290117-6adf9200-a793-11eb-99c9-baba1d8b7916.png)
I drew a red square of what I'm using for image detection, the size may change from one to another pet, you just need to screenshot an unique piece of the sprite, remember the imagelist library does not include any tolerance settings, since flash can be tricky with graphics it may not detect the sprite in some rare cases.
![image](https://user-images.githubusercontent.com/37041587/116290531-d6c1fa80-a793-11eb-8502-a9d876ab7b93.png)
This is the final result, I haven't tested which file extension (bmp, png or jpeg) works better but I always used png without any problem, if the sprite is never detected just take a breathe and screenshot / crop the sprite again.
![image](https://user-images.githubusercontent.com/37041587/116290695-07a22f80-a794-11eb-9417-022e46564dce.png) <- This is an image, a tiny tiny image
Sorry again for the delay, hope you managed to fix your issue.
